### ISSUE TITLE
复制大文件时会将文件保存在用户目录下一份，造成浪费

### ISSUE THREAD

**Issue by itning** [CrossPaste/crosspaste-desktop#1623]
### How frequently does the bug occur?

Always

### Description

1.我把GTA5从C盘拷贝到D盘
2.复制时发现C盘容量变小
3.通过分析工具发现会多出一个副本。
![image](https://github.com/user-attachments/assets/8ae28c93-3602-478f-a71d-7534d3f7795f)
![image](https://github.com/user-attachments/assets/ce5ffc08-4f83-497e-a3f1-b3a1191fba25)

### Can you reproduce the bug?

Always

### Version

1.0.5

### OS

windows 11

**Comment by guiyanakuang** [comment]
Thank you very much for reporting it. This is a bug that needs urgent attention, an unforeseen situation.

**Comment by guiyanakuang** [comment]
@itning 
Currently supports setting the maximum backup file size (default 32M, if exceeded, only the URL is recorded without performing a backup)
Supports setting the maximum synchronization file size (default 512M)
Supports customizing the storage path

These features will be released in the next version
