### ISSUE TITLE
部分软件（如 VS Code ）回车无响应，无法粘贴

### ISSUE THREAD

**Issue by ageovb** [CrossPaste/crosspaste-desktop#1632]
### Description

同时建议增加双击选项复制功能
日志已上传
[crosspaste.log](https://github.com/user-attachments/files/16521460/crosspaste.log)

### Version

1.0.5

### OS

Windows 10

**Comment by guiyanakuang** [comment]
@ageovb  感谢你报告这个问题
可以提供更多信息吗？
1. 是拷贝 html rtf 类型吗，自动粘贴到 vscode 失败吗？
2. 是每次都失败还是偶尔？
3. 回车粘贴失败，这个时候粘贴板成功替换了吗？还是说只是焦点转移出现了问题？

**Comment by guiyanakuang** [comment]
@ageovb  感谢你报告这个问题
可以提供更多信息吗？
1. 是拷贝 html rtf 类型吗，自动粘贴到 vscode 失败吗？
2. 是每次都失败还是偶尔？
3. 回车粘贴失败，这个时候粘贴板成功替换了吗？还是说只是焦点转移出现了问题？

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@ageovb thanks for reporting this issue
Can you provide more information?
1. Is it copying the html rtf type? Does it fail to automatically paste into vscode?
2. Does it fail every time or occasionally?
3. Paste fails when pressing Enter. Is the pasteboard successfully replaced at this time? Or is there just a problem with the focus shift?

**Comment by ageovb** [comment]
任何类型都不行，总是失败，而且剪贴板没有被替换

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Doesn't work for any type, always fails and the clipboard is not replaced

**Comment by guiyanakuang** [comment]
https://github.com/user-attachments/assets/27a44f88-b101-4209-8218-ca0025788168

@ageovb 就像这个视频一样，选中粘贴板，接下来回车，没有粘贴成功，并且没有设置当前粘贴板。但是目标软件不是 vscode 就可能成功。我的理解正确吗？

如果是这样，让我有些困惑，按理说目标软件不应该影响粘贴板的设置，最大的问题是焦点的转移

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
https://github.com/user-attachments/assets/27a44f88-b101-4209-8218-ca0025788168

@ageovb Just like this video, select the pasteboard and press Enter. The paste is not successful, and the current pasteboard is not set. But it may be successful if the target software is not vscode. Is my understanding correct?

If so, it makes me a little confused. Logically speaking, the target software should not affect the settings of the pasteboard. The biggest problem is the shift of focus.

**Comment by guiyanakuang** [comment]
I've reproduced this issue on Windows 11. Let me investigate why it's happening and how to fix it.

**Comment by guiyanakuang** [comment]
@ageovb. I believe this issue has been resolved through #1651. You can verify this by [running the app from the source code on the main branch](https://github.com/CrossPaste/crosspaste-desktop?tab=readme-ov-file#-getting-started-with-development), or by waiting for version 1.06 (which will be released soon). In any case, thank you very much for reporting this issue.
