### ISSUE TITLE
Do you have plans to support Android and iOS?

### ISSUE THREAD

**Issue by liaokaime** [CrossPaste/crosspaste-desktop#1693]
### How important is this improvement for you?

Would be a major improvement

**Comment by guiyanakuang** [comment]
Yes, the mobile version is actively being developed. Stay tuned!

**Comment by LTAND** [comment]
> Yes, the mobile version is actively being developed. Stay tuned!

Do you have an estimated completion time for the development

**Comment by guiyanakuang** [comment]
> > Yes, the mobile version is actively being developed. Stay tuned!
> 
> Do you have an estimated completion time for the development

The desktop and mobile versions are being developed in parallel, but I'm not sure how much longer it will take, perhaps one to two months if things go smoothly.

**Comment by guiyanakuang** [comment]
@liaokaime Thank you for your sponsorship. This is the first Github sponsor donation for the Crosspaste project. It truly encourages me to continue contributing to this open-source project. Once I finish the features for the current version, I plan to display a sponsors wall in the readme. In any case, thank you very much for your support.
