### ISSUE TITLE
Mac cannot recognize Windows, but Windows can recognize Mac

### ISSUE THREAD

**Issue by qpf521** [CrossPaste/crosspaste-desktop#1697]
### How frequently does the bug occur?

-- select --

### Description

Mac cannot recognize Windows, but Windows can recognize Mac. When connected through Windows, Windows displays a successful connection, but Mac displays a failed connection.

### Can you reproduce the bug?

Always

### Version

1.0.6

### OS

Mac（Apple silicon），Windows

**Comment by guiyanakuang** [comment]
<img width="426" alt="image" src="https://github.com/user-attachments/assets/1daf2318-e87d-464d-adea-75d2662aac20">
@qpf521 In Settings -> Network, you can view the IP addresses and ports of two devices. Can they telnet to each other? Also, if you have multiple routers in a mesh network, this situation might occur as well.

**Comment by qpf521** [comment]
Is this the problem with my Windows app settings - Network - IP address displaying N/A? In my Mac application, settings - Network - IP address display shows the correct IP address.Also, I only have one router.
![23791723816222_ pic](https://github.com/user-attachments/assets/3d06cba0-3121-49f0-8381-d952571f0c58)

**Comment by guiyanakuang** [comment]
Thank you very much for your feedback. This is a bug where the Windows client failed to obtain the local IP address. Please help by running this command in cmd:
```
wmic nicconfig where "IPEnabled=TRUE" get IPAddress
```
Let me see the results so I can identify the cause.
Also, what is the Mac IP address?

**Comment by qpf521** [comment]
Thank you for your help!
![23811723816883_ pic](https://github.com/user-attachments/assets/33259bcf-7f03-4311-9595-56a520f90b7c)
![23821723816894_ pic](https://github.com/user-attachments/assets/109b3f64-21bc-42aa-afe9-fdff6feceefa)
The black image is for Windows, and the software screenshot is for Mac.

**Comment by qpf521** [comment]
Hello, it's strange that Mac can suddenly scan Windows, but Windows settings - Network - IP address is still N/A. Moreover, when taking screenshots from Windows and pasting them from Mac, the file name of the image will also be pasted in, which may be a bug.
