### ISSUE TITLE
crash on kubuntu22.04

### ISSUE THREAD

**Issue by wieniawski-lai** [CrossPaste/crosspaste-desktop#1715]
### How frequently does the bug occur?

Always

### Description

While click the system tray icon, the software crashes.

### Stacktrace & log output

```shell
Signal Handlers:
   SIGSEGV: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, unblocked
    SIGBUS: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, unblocked
    SIGFPE: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, unblocked
   SIGPIPE: SIG_IGN, mask=00000000000010000000000000000000, flags=SA_RESTART, blocked
  *** Handler was modified!
  *** Expected: javaSignalHandler in libjvm.so, mask=11100100110111111111111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGXFSZ: javaSignalHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, blocked
    SIGILL: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, unblocked
   SIGUSR2: SR_handler in libjvm.so, mask=00000000000000000000000000000000, flags=SA_RESTART|SA_SIGINFO, blocked
    SIGHUP: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, blocked
    SIGINT: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, blocked
   SIGTERM: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, blocked
   SIGQUIT: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, blocked
   SIGTRAP: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO, unblocked
```

### Can you reproduce the bug?

Always

### Version

1.0.6

### OS

kubuntu22.04

**Comment by guiyanakuang** [comment]
@wieniawski-lai Thank you for reporting this error.

I conducted some research

https://bugs.openjdk.org/browse/JDK-8292054

I found a similar error here, which appears to be an issue between JDK and Ubuntu/Gtk. After comparing the fix changes, it doesn't appear in `JBR 17.0.11-b1312.2`, which CrossPaste uses as its runtime environment. Therefore, it's reasonable to suspect that JBR might not have merged the corresponding patch.

**Comment by wieniawski-lai** [comment]
en,

I tried to change my JRE into 17.0.6 (not openJDK, but from oracle), and same crash happens. And here is the complete log
[hs_err_pid6371.log](https://github.com/user-attachments/files/16702818/hs_err_pid6371.log)

**Comment by guiyanakuang** [comment]
I've reported this error to SystemTray. 

https://github.com/dorkbox/SystemTray/issues/220

This issue could potentially be related to SystemTray, or it might be related to the graphics driver. Either way, it's a tricky problem to solve. 😂

**Comment by guiyanakuang** [comment]
@wieniawski-lai  This issue occurs when SystemTray uses the GTK-type tray. In the upcoming release (version 1.0.8), SystemTray will default to using the AppIndicator type, which should circumvent this issue.

**Comment by guiyanakuang** [comment]
@wieniawski-lai  Version 1.0.8 has been released. 
```
wget https://github.com/CrossPaste/crosspaste-desktop/releases/download/1.0.8.925/crosspaste_1.0.8-925_amd64.deb
sudo apt install ./crosspaste_1.0.8-925_amd64.deb
```

You can install it using the method described above. I believe this version has fixed the application crash issue.

**Comment by wieniawski-lai** [comment]
> @wieniawski-lai Version 1.0.8 has been released.
> 
> ```
> wget https://github.com/CrossPaste/crosspaste-desktop/releases/download/1.0.8.925/crosspaste_1.0.8-925_amd64.deb
> sudo apt install ./crosspaste_1.0.8-925_amd64.deb
> ```
> 
> You can install it using the method described above. I believe this version has fixed the application crash issue.

thx, I have tried the new version. The bug seems fixed.
