### ISSUE TITLE
Occupying high RAM on both Windows and macOS

### ISSUE THREAD

**Issue by S1ashG** [CrossPaste/crosspaste-desktop#1716]
### How frequently does the bug occur?

Always

### Description

It takes up more than 800MB RAM while the store only contains data less than 50MB. Please optimize the RAM usage situation. 

<img width="851" alt="image" src="https://github.com/user-attachments/assets/202883e2-d18c-497b-8108-752358a6bba7">
<img width="432" alt="image" src="https://github.com/user-attachments/assets/3936f689-4590-4621-bb29-2292893a7cd7">

The Windows version has the same issue. It takes up more than 400MB RAM while store has less than 50MB data. 

### Can you reproduce the bug?

Always

### Version

1.0.6(862)

### OS

macOS Sonoma 14.5

**Comment by S1ashG** [comment]
Please add the label "Optimize". Thanks.

**Comment by S1ashG** [comment]
Please add the tag "Optimize". Thanks.

**Comment by guiyanakuang** [comment]
@S1ashG Thank you for reporting this issue. As this is a duplicate issue, I will close it later.
I plan to address the memory optimization in version 1.0.8.
