### ISSUE TITLE
Implement native macOS API for thumbnail generation

### ISSUE THREAD

**Issue by guiyanakuang** [CrossPaste/crosspaste-desktop#1906]
Improve performance, especially for large images

**Comment by sunxiang0918** [comment]
I guess skia is not a macOS-specific problem, and may have the same problem on other operating systems. However, I do not have the environment for other operating systems and cannot test it.

**Comment by guiyanakuang** [comment]
@sunxiang0918 Yes, I agree with your point. Issue #1880 has not been closed. Regarding the thumbnail issues on Windows and Linux, we can continue the discussion here.

**Comment by sunxiang0918** [comment]
oh,I see
