### ISSUE TITLE
IP show NA and cannot connetted

### ISSUE THREAD

**Issue by liuxiawei** [CrossPaste/crosspaste-desktop#2003]
### How frequently does the bug occur?

Always

### Description

![3cd33b37-eb01-4f3c-a813-e65f0173a916](https://github.com/user-attachments/assets/5b1710cc-5e8a-4475-9ae9-7a4b5dc9ecff)
Windows 11 Pro.
I tried the  FQA, It's ok in linux and found the IP of windows
But in Win11,The IP show "NA"， and not found any device And cannnot conntect even manully specify the IP of Linux
![图片](https://github.com/user-attachments/assets/7ea58c1c-28be-4f98-9a05-bd6f43608827)

![图片](https://github.com/user-attachments/assets/a40c6c73-48b2-4982-a70a-2529e37eef61)
The soft Barrier which based Bonjour is work right

### Can you reproduce the bug?

Always

### Version

1.0.10(1001)

### OS

windows11 pro

**Comment by guiyanakuang** [comment]
<img width="424" alt="image" src="https://github.com/user-attachments/assets/ab1af3d4-8bfb-403c-86fa-806f001836e9">

@liuxiawei. Thank you for reporting this issue. Please restart the Windows application, enable debug mode, then check network info and upload debug logs. This can help identify why the local IP address is not being obtained.

**Comment by guiyanakuang** [comment]
> ![图片](https://github.com/user-attachments/assets/a40c6c73-48b2-4982-a70a-2529e37eef61)

From the screenshot, it appears there's only one entry under Linux, which seems to indicate it only discovered itself.
Please confirm that both devices are on the same local network. A simple way to check this is: can they ping each other?

**Comment by liuxiawei** [comment]
Thanks for response. I checked the IP. it really has error and I fix it. But the new bug comeout:
windows can connected linux (IP show right), and Linux cannot connect win10 (IP error) but it can be added.
![图片](https://github.com/user-attachments/assets/080e9f0e-9c98-47e2-adf8-afc34e76ccb3)
![图片](https://github.com/user-attachments/assets/bce1d5ba-817a-4695-989c-5d9e48b272e6)
And I'm sorry that I cannnot found where open debug mode

**Comment by guiyanakuang** [comment]
I apologize, the debug feature will be released in the next version. It looks like the issue you're experiencing is the same as [#1981](https://github.com/CrossPaste/crosspaste-desktop/issues/1918#issuecomment-2367806959), which has been fixed but hasn't been officially released yet.

You can download a temporary version to verify the fix.
[crosspaste-1.0.10-1013-windows-amd64.zip](https://oss.crosspaste.com/1.0.10.1013/crosspaste-1.0.10-1013-windows-amd64.zip)

**Comment by liuxiawei** [comment]
The bug dispear in 1013. Thanks for the help!
