### ISSUE TITLE
Double click of main windows item Feature Request

### ISSUE THREAD

**Issue by liuxiawei** [CrossPaste/crosspaste-desktop#2012]
### Solution

在CopyQ等软件中，可通过快捷键召唤出粘帖列表后直接双击，以达到快速切换的目的，建议crosspaste也采取

### How important is this improvement for you?

Would be a major improvement

**Comment by guiyanakuang** [comment]
![image](https://github.com/user-attachments/assets/a5b22421-95b9-4241-b760-2008283c628a)
Currently, it supports using a keyboard shortcut to bring up the search window, selecting a paste item, and pressing Enter to paste across different applications.
Are you referring to adding a mouse double-click trigger method?

**Comment by liuxiawei** [comment]
无论是搜索界面还是主界面，均难以达到快速在多个粘帖选项中选择选项的目的。在copyQ中能够快速的实现快捷键召唤主界面list,然后双击需要粘贴选项即可快速选择粘贴选项并自动将选项替换默认粘帖板（crosspaste已实现）和直接达到粘贴目的（目前crosspaste尚未实现，双击后只替换了粘帖版，需要再ctrl+V一次）。

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Whether it is the search interface or the main interface, it is difficult to quickly select options among multiple paste options. In copyQ, you can quickly use shortcut keys to summon the main interface list, and then double-click the option you want to paste to quickly select the paste option and automatically replace the option with the default paste board (crosspaste has been implemented) and directly achieve the purpose of pasting (currently crosspaste has not been implemented, After double-clicking, only the pasted version is replaced, and you need to ctrl+V again).

**Comment by guiyanakuang** [comment]
@liuxiawei Thank you for your suggestion. I think we can add this feature in the next version.

**Comment by guiyanakuang** [comment]
This feature has already been implemented in #2021. The latest released version will include this functionality.

**Comment by guiyanakuang** [comment]
@BlipRanger, Currently, we already support custom hotkeys, including using Win + V to bring up the search window. For the next version, I think it would be a good idea to implement double-click as an alternative to pressing Enter for pasting items from the search window.
