### ISSUE TITLE
Add click-to-copy feature for pasteboard

### ISSUE THREAD

**Issue by blogj** [CrossPaste/crosspaste-desktop#2185]
### Solution

每次去找拷贝按钮都需要点击右下角小图标然后再找到右上角三个点再找到拷贝按钮点击。

### Alternatives

能否定直接简化2步桌面右下角图标点击，鼠标左击需要拷贝的条目空白处就拷贝了

### How important is this improvement for you?

Fairly niche but nice to have anyway

**Comment by guiyanakuang** [comment]
<img width="429" alt="image" src="https://github.com/user-attachments/assets/2a8d75e6-31db-44b4-80e4-b5ba8c5578b0">

@blogj, Thank you for your suggestions for improvement. Currently, we support right-click menu for selecting specific operations and double-click for quick paste (cross-application automatic paste). Single left-click for copy is also quite intuitive - I'll add this feature in the next version:

1. Double-click the clipboard in the main interface
2. Use shortcut to bring up the search window, select the corresponding clipboard, and press enter

Perhaps the documentation doesn't clearly point out these features?

------

感谢你提出改进意见，目前支持右键菜单来选择具体的操作，和双击快捷粘贴（跨软件自动粘贴），左键单击拷贝也比较符合直觉，让我在下个版本加入这个功能。

另外为什么不直接使用跨软件粘贴呢？目前支持两种方式快捷粘贴
1. 在主界面双击粘贴板
2. 快捷方式唤出搜索窗，选择对应的粘贴板，回车

是不是文档还不够清晰的指出这些特性？
