### ISSUE TITLE
Cannot customize storage directory

### ISSUE THREAD

**Issue by KuangXiaoYan** [CrossPaste/crosspaste-desktop#2261]
### How frequently does the bug occur?

-- select --

### Description

在设置存储路劲的时候提示错误，选择其他的目录就会出现下面错误
![error](https://github.com/user-attachments/assets/89ac1a0a-a959-4472-8841-07b582a038c2)

### Can you reproduce the bug?

-- select --

### Version

1.0.13

### OS

Windows

**Comment by guiyanakuang** [comment]
The error message indicates that the custom directory must be empty when setting it as the storage location. You can simply create a new empty directory and use that for CrossPaste storage.

**Comment by guiyanakuang** [comment]
I believe selecting the correct directory should resolve this issue. I'll close this issue for now. If the problem persists, we can reopen it.
