### ISSUE TITLE
Increase touch targets size according to Google Play pre-launch report

### ISSUE THREAD

**Issue by guiyanakuang** [CrossPaste/crosspaste-desktop#2305]
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e2da4fe1-cfb7-4501-b735-52fb3a04449b" />

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e2da4fe1-cfb7-4501-b735-52fb3a04449b" />
